### ISSUE TITLE
Bitcode

### ISSUE THREAD

**Issue by dengwant** [akshetpandey/Cronet.framework#1]
Is the framework support bitcode. if not,how can I build one to support it 
Thanks!

**Comment by akshetpandey** [comment]
Hi @dengwant, unfortunately bitcode is not supported in the version published to cocoapods.
Google by default doesn't build bitcode enabled builds for cronet, although it should be possible to build one yourself. You can follow build instructions here: https://chromium.googlesource.com/chromium/src/+/master/docs/ios/build_instructions.md
Cronet build config is here:
https://chromium.googlesource.com/chromium/src/+/HEAD/components/cronet/ios/BUILD.gn
Make sure to enable bitcode here:
https://chromium.googlesource.com/chromium/src/build/config/+/refs/heads/master/ios/BUILD.gn#24

**Comment by dengwant** [comment]
Thanks for your reply，I will try it.
Another question, when I enable QUIC,I can upload task success,but I can't receive 【- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task
   didSendBodyData:(int64_t)bytesSent
    totalBytesSent:(int64_t)totalBytesSent
totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend】protocol，but others e.g.[- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error] work well

**Comment by akshetpandey** [comment]
I am not surprised that the objc interface of cronet doesn't implement the [didSendBodyData](https://developer.apple.com/documentation/foundation/nsurlsessiontaskdelegate/1408299-urlsession?language=objc) api. Unfortunately, the best you can do is open a ticket on the chromium issue tracker.

**Comment by dengwant** [comment]
I got it，thanks.
