### ISSUE TITLE
Debug info for static lib?

### ISSUE THREAD

**Issue by CodeLife2012** [akshetpandey/Cronet.framework#2]
The dSYM released should be only  work with the dynamic framework.

**Comment by akshetpandey** [comment]
Yes, that is expected, the dSYM exported is only for the dynamic framework. I am sorry the file name should have been more explicit about this.

**Comment by CodeLife2012** [comment]
My problem is static lib don't contain debug info @akshetpandey

**Comment by akshetpandey** [comment]
Yes, as I mentioned in the previous answer, debug symbols are only available for the dynamic library.
You will have to build your own cronet static library with the appropriate flags if you want debug symbols for it.
Starting Instructions can be found here: https://chromium.googlesource.com/chromium/src/+/master/components/cronet/ios/docs/BUILD.md
You can figure out what flags to use here: https://chromium.googlesource.com/chromium/src/+/master/components/cronet/ios/BUILD.gn#217

**Comment by CodeLife2012** [comment]
OK, close it. Thanks
