### ISSUE TITLE
DTXcodeBuild中包含的12A8179i_audio无法通过苹果审核

### ISSUE THREAD

**Issue by itdongbaojun** [akshetpandey/Cronet.framework#4]
DTXcodeBuild中包含的12A8179i_audio无法通过苹果审核，尽快升级一下，已经收到苹果的反馈。

**Comment by akshetpandey** [comment]
Ahh interesting, sorry about that. 
Looks like its being tracked here: https://groups.google.com/a/chromium.org/g/chromium-reviews/c/mTKEahlSER4 and is already fixed.

You can either use `85.0.4183.109` for now or use `87.0.4280.27-beta` which should be available in the stable channel soon

**Comment by itdongbaojun** [comment]
ok，thks
