### ISSUE TITLE
86.xx.xx.xx不再支持iOS9

### ISSUE THREAD

**Issue by itdongbaojun** [akshetpandey/Cronet.framework#5]
需要留意一下一下，官方版本从85.xx.xx.xx上级到86.xx.xx.xx后不再支持iOS9，从iOS10开始支持了。刚刚踩过的坑。

**Comment by akshetpandey** [comment]
Yes google  did remove support for iOS9 : https://chromium.googlesource.com/chromium/src/+/1d831f0788ac200b96f02e08229110de5f9939e9

But if  you want  to keep  supporting iOS9 you can stick to an older version. Cronet doesn't get too many updates across chrome versions.

Subset of cronet changes are here: https://chromium.googlesource.com/chromium/src/+log/master/components/cronet

**Comment by itdongbaojun** [comment]
@akshetpandey thks，we use the latest 85.xx.xx.xx version
