### ISSUE TITLE
Is it suspended?

### ISSUE THREAD

**Issue by li6185377** [akshetpandey/Cronet.framework#6]
This project is great 👍👍👍, but isn't it updated?

**Comment by akshetpandey** [comment]
Do you mean to new cronet versions? The latest stable was published 27 days ago. Changes on the master branch are a bit misleading as those are just build scripts and don't require changes for a while. 

See: https://github.com/akshetpandey/Cronet.framework/branches/

There is an ongoing issue with beta/dev and I am waiting for a fix from google for it.
